name: dart_doc_bot
description: A bot that generates, store and search documentation for Dart/Flutter project.

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  http: ^1.1.0
  drift: ^2.11.0
  meta: ^1.7.0
  multiline: ^3.0.0
  path: ^1.8.1
  rxdart: ^0.27.7
  collection: ^1.17.1
  stack_trace: ^1.11.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_proxy: ^1.0.2
  shelf_static: ^1.1.1
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.11.0
  lint: ^2.0.1
  file: ^7.0.0
